# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "refactor", "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: |
          **/requirements.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with pytest
      env:
        GITHUB_TOKEN: ${{ secrets.MODEL_TOKEN }}
        ADS_API_KEY: ${{ secrets.ADS_API_KEY }}
        TEST: ${{ secrets.TEST }}
      run: |
        echo $TEST
        pytest
