# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "refactor", "pipeline-test" ]
  pull_request:
    branches: [ "pipeline-test" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: TEST_ENV
    env:
      GITHUB_TOKEN: ${{ secrets.MODEL_TOKEN }}
      ADS_API_KEY: ${{ secrets.ADS_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        echo "Running tests"
        # pytest
